map: data/maps/simple_room.npy
sff: data/sff/distance_L1.npy
N: 100

params:
  k_S: 3
  k_D: 1
  diffuse: 0.2
  decay: 0.2
  # neighborhood: moore
  neighborhood: neumann
  k_A: 3
  # optional tuning
  congestion_tax: 0.20
  congestion_tax_exempt_exit: true
  local_front_density_mu: 0.02
  max_steps: 500

seed: 42
